config/routes.rb
TesisLab::Application.routes.draw do
  resources :fuente_bibliograficas, :only => [:create, :new]
  resources :compromisos, :only => [:create, :new]
  resources :reunione, :only => [:list, :new, :create]  do

    resources :tesis
  end
  resources :estudiantes  do
    resources :tesis
  end

  resources :anotacions, :only => [:create, :new]

  resources :archivos, :only => [:new, :create]
  match '/archivos/confirmacion' => 'archivos#confirmacion'
  match '/archivos' => 'archivos#index'

  resources :temas, :only => [:new, :create]
  match '/fuente_bibliograficas' => 'fuente_bibliograficas#index'

  match '/fuente_bibliograficas/list' => 'fuente_bibliograficas#list'
  match '/fuente_bibliograficas/creado' => 'fuente_bibliograficas#create'
  match '/fuente_bibliograficas/get_all' =>'fuente_bibliograficas#get_all'

  match '/bibliografia'=>'fuente_bibliograficas#bibliografia'
  match '/temas/confirm'=>'temas#confirm'
  match '/compromisos/list' => 'compromisos#list'
  match '/compromisos/:ID/list' => 'compromisos#compromiso_estudiante'
  match '/compromisos/creado' => 'compromisos#create'
  match '/compromisos/eventos' => 'compromisos#eventos'
  match '/compromisos/:id/edit' => 'compromisos#edit'
  match '/compromisos/:id/update' => 'compromisos#update'
  match '/compromisos'=>'compromisos#index'

  resources :tag, :only => [:new, :create]
  match '/tag'=>'tag#index'
  match '/tag/buscar' => 'tag#buscar'
  match '/tag/fuentes' => 'tag#fuentes', :as => 'fuentes'
  match '/tag/entregables' => 'tag#archivos', :as => 'archivos'
  match '/tag/reuniones' => 'tag#reuniones', :as => 'reuniones'
  match '/tag/temas' => 'tag#temas', :as => 'temas'
  match '/tag/compromisos' => 'tag#compromisos', :as => 'compromisos'
  match '/tag/confirma' => 'tag#confirma'
  match '/tag/asignar' => 'tag#asignar'
  match '/tag/parcial' => 'tag#parcial'
  match '/tag/conf' => 'tag#conf'

  match '/entregables/list' => 'entregable#list'
  match '/estudiantes' => 'estudiantes#index'
  match '/reuniones' => 'reunione#index'
  match '/reuniones/list' => 'reunione#list'
  match '/reuniones/:id/edit' => 'reunione#edit'
  match '/reuniones/:id/update' => 'reunione#update'
  match '/anotacions/list' => 'anotacions#list'
  match '/anotacions/:fuenteid' => 'anotacions#show'

  match '/reuniones/new' => 'reunione#new'
  match '/reuniones' => 'reunione#create'

  match '/login' => 'login#index'
  match '/login/login' => 'login#login'
  match '/login/create' => 'login#creartesis'
  match '/profesores' => 'profesores#index'
  match '/tesis/create' => 'tesis#creartesis'
  match '/tesis/:id' => 'tesis#show'
  match '/temas/add' => 'fuente_bibliograficas#add'
  match '/temas/assigned' => 'fuente_bibliograficas#added'

  match '/index_estudiantes' => 'login#bienvenidae'

  root :to => 'login#index'

end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
  attr_accessible :CODIGO, :id, :PRIMER_APELLIDO, :PRIMER_NOMBRE, :SEGUNDO_APELLIDO, :SEGUNDO_NOMBRE, :USUARIO
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  # GET /estudiantes
  # GET /estudiantes.json
  def index
    @estudiantes = Estudiante.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estudiantes }
    end
  end

  # GET /estudiantes/1
  # GET /estudiantes/1.json
  def show
    @estudiante = Estudiante.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @estudiante }
    end
  end

  # GET /estudiantes/new
  # GET /estudiantes/new.json
  def new
    @estudiante = Estudiante.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estudiante }
    end
  end

  # GET /estudiantes/1/edit
  def edit
    @estudiante = Estudiante.find(params[:id])
  end

  # POST /estudiantes
  # POST /estudiantes.json
  def create
    @estudiante = Estudiante.new(params[:estudiante])

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully created.' }
        format.json { render json: @estudiante, status: :created, location: @estudiante }
      else
        format.html { render action: "new" }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /estudiantes/1
  # PUT /estudiantes/1.json
  def update
    @estudiante = Estudiante.find(params[:id])

    respond_to do |format|
      if @estudiante.update_attributes(params[:estudiante])
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1
  # DELETE /estudiantes/1.json
  def destroy
    @estudiante = Estudiante.find(params[:id])
    @estudiante.destroy

    respond_to do |format|
      format.html { redirect_to estudiantes_url }
      format.json { head :no_content }
    end
  end
end

app/views/estudiantes/_form.html.erb
<%= form_for(@estudiante) do |f| %>
  <% if @estudiante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estudiante.errors.count, "error") %> prohibited this estudiante from being saved:</h2>

      <ul>
      <% @estudiante.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :PRIMER_NOMBRE %><br />
    <%= f.text_field :PRIMER_NOMBRE %>
  </div>
  <div class="field">
    <%= f.label :SEGUNDO_NOMBRE %><br />
    <%= f.text_field :SEGUNDO_NOMBRE %>
  </div>
  <div class="field">
    <%= f.label :PRIMER_APELLIDO %><br />
    <%= f.text_field :PRIMER_APELLIDO %>
  </div>
  <div class="field">
    <%= f.label :SEGUNDO_APELLIDO %><br />
    <%= f.text_field :SEGUNDO_APELLIDO %>
  </div>
  <div class="field">
    <%= f.label :CODIGO %><br />
    <%= f.text_field :CODIGO %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estudiantes/edit.html.erb
<h1>Editar estudiante</h1>

<%= render 'form' %>

<%= link_to 'Show', @estudiante %> |
<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/index.html.erb
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
<link href='/fullcalendar/fullcalendar.css' rel='stylesheet' />
<link href='/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />
<script src='/fullcalendar/fullcalendar.min.js'></script>

<style>
    body { font-size: 62.5%; }
    label, input { display:block; }
    input.text { margin-bottom:12px; width:95%; padding: .4em; }
    fieldset { padding:0; border:0; margin-top:25px; }
    h1 { font-size: 1.2em; margin: .6em 0; }
    div#users-contain { width: 350px; margin: 20px 0; }
    div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
    div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
</style>
<script>
    $(function() {
        var nombre = $( "#nombre" ),
                descripcion = $( "#descripcion" ),
                allFields = $( [] ).add( nombre ).add( descripcion ),
                tips = $( ".validateTips" );

        function updateTips( t ) {
            tips
                    .text( t )
                    .addClass( "ui-state-highlight" );
            setTimeout(function() {
                tips.removeClass( "ui-state-highlight", 1500 );
            }, 500 );
        }

        function checkLength( o, n, min, max ) {
            if ( o.val().length > max || o.val().length < min ) {
                o.addClass( "ui-state-error" );
                updateTips( "Length of " + n + " must be between " +
                        min + " and " + max + "." );
                return false;
            } else {
                return true;
            }
        }

        function checkRegexp( o, regexp, n ) {
            if ( !( regexp.test( o.val() ) ) ) {
                o.addClass( "ui-state-error" );
                updateTips( n );
                return false;
            } else {
                return true;
            }
        }


        $( "#create-acta" )
                .button()
                .click(function() {
                    window.location.href = "/reuniones/new";
                });

        $( "#create-compromiso" )
                .button()
                .click(function() {
                    window.location.href = "/compromisos/new";
                });
        $( "#create-tema" )
                .button()
                .click(function() {
                    window.location.href = "/temas/new";
                });
        $( "#create-fuente" )
                .button()
                .click(function() {
                    window.location.href = "/fuente_bibliograficas/new";
                });
    });
</script>
<script>

    $(document).ready(function() {

        $('#calendar').fullCalendar({

            editable: false,

            events: "/compromisos/eventos.json",

            eventDrop: function(event, delta) {
                // alert(event.title + ' was moved ' + delta + ' days\n' +
                //         '(should probably update your database)');
            },

            loading: function(bool) {
                if (bool) $('#loading').show();
                else $('#loading').hide();
            }

        });


    });

</script>

</head>
<div class="container">




  <div class="easyui-layout" style="width:1000px;height:600px;">
    <div data-options="region:'north'" style="height:50px">

    </div>
    <div data-options="region:'south',split:true" style="height:50px;"></div>
    <div data-options="region:'east',split:true" title="Compromisos" style="width:580px;">
      <div id='calendar'></div>
    </div>
    <div data-options="region:'west',split:true" title="Estudiante" style="width:120px;">

      <button id="create-acta"  ><img border=0 src="/assets/acta.png">Crear acta de reunion</button>
      <button id="create-compromiso"  ><img border=0 src="/assets/compromiso.png">Crear compromiso</button>
      <button id="create-tema"  ><img border=0 src="/assets/tema.png">Crear tema</button>
      <button id="create-fuente"  ><img border=0 src="/assets/fuente.png">Crear fuente</button>



    </div>
    <div data-options="region:'center',title:'Gestion de tesis',iconCls:'icon-ok'">


      <div class="easyui-accordion" style="width:300px;height:400px;">
        <div title="Manejo de fuentes" data-options="iconCls:'icon-search'" style="overflow:auto;padding:10px;">

          <ul class="easyui-tree">
            <li><h4><%= link_to 'Agregar una Fuente Bibliográfica', '/fuente_bibliograficas/new' %></li>
            <li><h4><%= link_to 'Ver Fuentes Bibliográficas', '/fuente_bibliograficas/list' %></li>
            <li><h4><%= link_to 'Agregar Tema', '/temas/new' %></li>
            <li><h4><%= link_to 'Asignar Tema', '/temas/add' %></li>
            <li><h4><%= link_to 'Obtener Bibliografía', '/fuente_bibliograficas/get_all' %></li>
          </ul>

        </div>
        <div title="Manejo de compromisos" data-options="iconCls:'icon-search'" style="padding:10px;">

          <ul class="easyui-tree">
            <li><h4><%= link_to 'Crear Compromiso', '/compromisos/new' %></li>
            <li><h4><%= link_to 'Ver Compromisos', '/compromisos/list' %></li>
          </ul>
         </div>
        <div title="Manejo de entregables" data-options="iconCls:'icon-search'" style="padding:10px;">

          <ul class="easyui-tree">
            <li><h4><%= link_to 'Subir Entregables', '/archivos/new' %></li>
            <li><h4><%= link_to 'Ver entregables', '/entregables/list' %></li>
          </ul>
        </div>

        <div title="Manejo de compromisos" data-options="iconCls:'icon-search'" style="padding:10px;">

          <ul class="easyui-tree">
            <li><h4><%= link_to 'Crear Compromiso', '/compromisos/new' %></li>
            <li><h4><%= link_to 'Ver Compromisos', '/compromisos/list' %></li>
          </ul>
        </div>
        <div title="Manejo de reuniones" data-options="iconCls:'icon-search'" style="padding:10px;">

          <ul class="easyui-tree">
            <li><h4><%= link_to 'Manejo de Compromisos', '/fuente_bibliograficas' %></li>
            <li><h4><%= link_to 'Compromisos', '/tag/compromisos' %></li>
            <li><h4><%= link_to 'Temas', '/tag/temas' %></li>
            <li><h4><%= link_to 'Fuentes', '/tag/fuentes' %></li>
          </ul>
        </div>

        <div title="Asignacion de tags" data-options="iconCls:'icon-help'" style="padding:10px;">

          <ul class="easyui-tree">
            <li><h4><%= link_to 'Crear Tag', '/tag/new' %></li>
            <li><h4><%= link_to 'Asignar Tag', '/tag/asignar' %></li>
            <li><h4><%= link_to 'Buscar por Tag', '/tag/buscar' %></li>
          </ul>
        </div>

      </div>


    </div>
  </div>

</div>

app/views/estudiantes/new.html.erb
<h1>Nuevo estudiante</h1>

<%= render 'form' %>

<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Primer nombre:</b>
  <%= @estudiante.PRIMER_NOMBRE %>  <%= @estudiante.SEGUNDO_NOMBRE %>  <%= @estudiante.PRIMER_APELLIDO %>  <%= @estudiante.SEGUNDO_APELLIDO %>
</p>

<p>
  <b>Codigo:</b>
  <%= @estudiante.CODIGO %>
</p>



<% @tesises= Tesi.find_by_sql ["SELECT * FROM TESIS JOIN TESIS_ESTUDIANTES ON TESIS.ID=TESIS_ID WHERE ESTUDIANTE_ID=?", @estudiante.id]  %>

<% @tesises.each do |tesis1| -%>


    <p>
      <b>Nombre tesis:</b> <%= tesis1.NOMBRE%>
    </p>

    <p>
    <%= link_to "Tesis", :controller => "tesis", :action => "show", :id => tesis1.id %>
    </p>
<% end -%>

<%= link_to 'Editar', edit_estudiante_path(@estudiante) %> |
<%= link_to 'Regresar', estudiantes_path %>